In [35]:
from bokeh.io import  push_notebook, show, output_notebook
from bokeh.layouts import row
from bokeh.plotting import figure

# prepare some data
x = [0.1, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
y0 = [i**2 for i in x]
y1 = [10**i for i in x]
y2 = [10**(i**2) for i in x]

# output to static HTML file
output_notebook()

# create a new plot
p = figure(
   tools="pan,box_zoom,reset,save",
   y_axis_type="log", y_range=[0.001, 10**11], title="log axis example",
   x_axis_label='sections', y_axis_label='particles'
)

# add some renderers
p.line(x, x, legend="y=x")
p.circle(x, x, legend="y=x", fill_color="white", size=8)
p.line(x, y0, legend="y=x^2", line_width=3)
p.line(x, y1, legend="y=10^x", line_color="red")
p.circle(x, y1, legend="y=10^x", fill_color="red", line_color="red", size=6)
p.line(x, y2, legend="y=10^x^2", line_color="orange", line_dash="4 4")

# show the results
show(p)

RuntimeError: node.js is needed to allow compilation of custom models ("conda install -c bokeh nodejs" or follow https://nodejs.org/en/download/)

In [28]:
x

array([ 0.1       ,  0.42222222,  0.74444444,  1.06666667,  1.38888889,
        1.71111111,  2.03333333,  2.35555556,  2.67777778,  3.        ])

In [29]:
y

array([ 3.        ,  2.9921147 ,  2.96858316,  2.92977649,  2.87630668,
        2.80901699,  2.72896863,  2.63742399,  2.53582679,  2.42577929,
        2.30901699,  2.18738131,  2.06279052,  1.93720948,  1.81261869,
        1.69098301,  1.57422071,  1.46417321,  1.36257601,  1.27103137,
        1.19098301,  1.12369332,  1.07022351,  1.03141684,  1.0078853 ,
        1.        ,  1.0078853 ,  1.03141684,  1.07022351,  1.12369332,
        1.19098301,  1.27103137,  1.36257601,  1.46417321,  1.57422071,
        1.69098301,  1.81261869,  1.93720948,  2.06279052,  2.18738131,
        2.30901699,  2.42577929,  2.53582679,  2.63742399,  2.72896863,
        2.80901699,  2.87630668,  2.92977649,  2.96858316,  2.9921147 ,
        3.        ,  2.9921147 ,  2.96858316,  2.92977649,  2.87630668,
        2.80901699,  2.72896863,  2.63742399,  2.53582679,  2.42577929,
        2.30901699,  2.18738131,  2.06279052,  1.93720948,  1.81261869,
        1.69098301,  1.57422071,  1.46417321,  1.36257601,  1.27

In [30]:
x[0:-1]

array([ 0.1       ,  0.42222222,  0.74444444,  1.06666667,  1.38888889,
        1.71111111,  2.03333333,  2.35555556,  2.67777778])

In [34]:
x[0:3]

TypeError: 'numpy.ndarray' object is not callable